/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CConnectionIdRouteImport } from './routes/c.$connectionId'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as CConnectionIdIndexRouteImport } from './routes/c.$connectionId.index'
import { Route as CConnectionIdChatThreadIdRouteImport } from './routes/c.$connectionId.chat.$threadId'
import { Route as CConnectionIdSqlQueryIdRouteImport } from './routes/c.$connectionId.sql.$queryId'
import { Route as CConnectionIdTSchemaTableRouteImport } from './routes/c.$connectionId.t.$schema.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CConnectionIdRoute = CConnectionIdRouteImport.update({
  id: '/c/$connectionId',
  path: '/c/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const CConnectionIdIndexRoute = CConnectionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CConnectionIdRoute,
} as any)
const CConnectionIdChatThreadIdRoute =
  CConnectionIdChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => CConnectionIdRoute,
  } as any)
const CConnectionIdSqlQueryIdRoute = CConnectionIdSqlQueryIdRouteImport.update({
  id: '/sql/$queryId',
  path: '/sql/$queryId',
  getParentRoute: () => CConnectionIdRoute,
} as any)
const CConnectionIdTSchemaTableRoute =
  CConnectionIdTSchemaTableRouteImport.update({
    id: '/t/$schema/$table',
    path: '/t/$schema/$table',
    getParentRoute: () => CConnectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/c/$connectionId': typeof CConnectionIdRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/c/$connectionId/': typeof CConnectionIdIndexRoute
  '/c/$connectionId/chat/$threadId': typeof CConnectionIdChatThreadIdRoute
  '/c/$connectionId/sql/$queryId': typeof CConnectionIdSqlQueryIdRoute
  '/c/$connectionId/t/$schema/$table': typeof CConnectionIdTSchemaTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/c/$connectionId': typeof CConnectionIdIndexRoute
  '/c/$connectionId/chat/$threadId': typeof CConnectionIdChatThreadIdRoute
  '/c/$connectionId/sql/$queryId': typeof CConnectionIdSqlQueryIdRoute
  '/c/$connectionId/t/$schema/$table': typeof CConnectionIdTSchemaTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/c/$connectionId': typeof CConnectionIdRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/c/$connectionId/': typeof CConnectionIdIndexRoute
  '/c/$connectionId/chat/$threadId': typeof CConnectionIdChatThreadIdRoute
  '/c/$connectionId/sql/$queryId': typeof CConnectionIdSqlQueryIdRoute
  '/c/$connectionId/t/$schema/$table': typeof CConnectionIdTSchemaTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/c/$connectionId'
    | '/chat/$threadId'
    | '/c/$connectionId/'
    | '/c/$connectionId/chat/$threadId'
    | '/c/$connectionId/sql/$queryId'
    | '/c/$connectionId/t/$schema/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/chat/$threadId'
    | '/c/$connectionId'
    | '/c/$connectionId/chat/$threadId'
    | '/c/$connectionId/sql/$queryId'
    | '/c/$connectionId/t/$schema/$table'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/c/$connectionId'
    | '/chat/$threadId'
    | '/c/$connectionId/'
    | '/c/$connectionId/chat/$threadId'
    | '/c/$connectionId/sql/$queryId'
    | '/c/$connectionId/t/$schema/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CConnectionIdRoute: typeof CConnectionIdRouteWithChildren
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$connectionId': {
      id: '/c/$connectionId'
      path: '/c/$connectionId'
      fullPath: '/c/$connectionId'
      preLoaderRoute: typeof CConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$connectionId/': {
      id: '/c/$connectionId/'
      path: '/'
      fullPath: '/c/$connectionId/'
      preLoaderRoute: typeof CConnectionIdIndexRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/chat/$threadId': {
      id: '/c/$connectionId/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/c/$connectionId/chat/$threadId'
      preLoaderRoute: typeof CConnectionIdChatThreadIdRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/sql/$queryId': {
      id: '/c/$connectionId/sql/$queryId'
      path: '/sql/$queryId'
      fullPath: '/c/$connectionId/sql/$queryId'
      preLoaderRoute: typeof CConnectionIdSqlQueryIdRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/t/$schema/$table': {
      id: '/c/$connectionId/t/$schema/$table'
      path: '/t/$schema/$table'
      fullPath: '/c/$connectionId/t/$schema/$table'
      preLoaderRoute: typeof CConnectionIdTSchemaTableRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
  }
}

interface CConnectionIdRouteChildren {
  CConnectionIdIndexRoute: typeof CConnectionIdIndexRoute
  CConnectionIdChatThreadIdRoute: typeof CConnectionIdChatThreadIdRoute
  CConnectionIdSqlQueryIdRoute: typeof CConnectionIdSqlQueryIdRoute
  CConnectionIdTSchemaTableRoute: typeof CConnectionIdTSchemaTableRoute
}

const CConnectionIdRouteChildren: CConnectionIdRouteChildren = {
  CConnectionIdIndexRoute: CConnectionIdIndexRoute,
  CConnectionIdChatThreadIdRoute: CConnectionIdChatThreadIdRoute,
  CConnectionIdSqlQueryIdRoute: CConnectionIdSqlQueryIdRoute,
  CConnectionIdTSchemaTableRoute: CConnectionIdTSchemaTableRoute,
}

const CConnectionIdRouteWithChildren = CConnectionIdRoute._addFileChildren(
  CConnectionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CConnectionIdRoute: CConnectionIdRouteWithChildren,
  ChatThreadIdRoute: ChatThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
